// Code generated by protoc-gen-validate
// source: envoy/config/filter/http/session_manager/v1alpha/config.proto
// DO NOT EDIT!!!

package envoy_config_filter_http_session_manager_v1alpha

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"strings"
	"time"
	"unicode/utf8"

	"github.com/gogo/protobuf/types"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = types.DynamicAny{}
)

// Validate checks the field values on ForwardRule with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *ForwardRule) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetName()) < 1 {
		return ForwardRuleValidationError{
			Field:  "Name",
			Reason: "value length must be at least 1 bytes",
		}
	}

	if len(m.GetPreamble()) < 1 {
		return ForwardRuleValidationError{
			Field:  "Preamble",
			Reason: "value length must be at least 1 bytes",
		}
	}

	return nil
}

// ForwardRuleValidationError is the validation error returned by
// ForwardRule.Validate if the designated constraints aren't met.
type ForwardRuleValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e ForwardRuleValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForwardRule.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = ForwardRuleValidationError{}

// Validate checks the field values on TokenBinding with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *TokenBinding) Validate() error {
	if m == nil {
		return nil
	}

	if len(m.GetSecret()) > 44 {
		return TokenBindingValidationError{
			Field:  "Secret",
			Reason: "value length must be at most 44 bytes",
		}
	}

	// no validation rules for Token

	// no validation rules for Binding

	return nil
}

// TokenBindingValidationError is the validation error returned by
// TokenBinding.Validate if the designated constraints aren't met.
type TokenBindingValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e TokenBindingValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenBinding.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = TokenBindingValidationError{}

// Validate checks the field values on SessionManager with the rules defined in
// the proto definition for this message. If any rules are violated, an error
// is returned.
func (m *SessionManager) Validate() error {
	if m == nil {
		return nil
	}

	if v, ok := interface{}(m.GetTokenBinding()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SessionManagerValidationError{
				Field:  "TokenBinding",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	if v, ok := interface{}(m.GetForwardRule()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SessionManagerValidationError{
				Field:  "ForwardRule",
				Reason: "embedded message failed validation",
				Cause:  err,
			}
		}
	}

	return nil
}

// SessionManagerValidationError is the validation error returned by
// SessionManager.Validate if the designated constraints aren't met.
type SessionManagerValidationError struct {
	Field  string
	Reason string
	Cause  error
	Key    bool
}

// Error satisfies the builtin error interface
func (e SessionManagerValidationError) Error() string {
	cause := ""
	if e.Cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.Cause)
	}

	key := ""
	if e.Key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSessionManager.%s: %s%s",
		key,
		e.Field,
		e.Reason,
		cause)
}

var _ error = SessionManagerValidationError{}
